Files
asiajanicka/TravelAgency pull request #6
Opened 2022-12-17 16:04 UTC by asiajanicka

2022-12-23 14:42 UTC, vboltrukanis requested changes
do not use RuntimeException and small refactoring required

2022-12-23 14:42 UTC, vboltrukanis commented on src/main/java/org/jjm/TripBooking.java
> +            throw new RuntimeException(e);
do not use runtime exceptions like that

2022-12-23 14:42 UTC, vboltrukanis commented on src/main/java/org/jjm/TripBooking.java
> +            Utils.writeSessionStatisticsToFile("src/test/resources/tempStatistics.txt");
lets try to configure this path from config file

2022-12-23 14:42 UTC, vboltrukanis commented on src/main/java/org/jjm/bookings/TransportBooking.java
> +    private static int counter = 0;
what do you use this counter for?

2022-12-25 16:50 UTC, asiajanicka commented on src/main/java/org/jjm/TripBooking.java
> +            throw new RuntimeException(e);
changed

2022-12-25 16:53 UTC, asiajanicka commented on src/main/java/org/jjm/TripBooking.java
> +            Utils.writeSessionStatisticsToFile("src/test/resources/tempStatistics.txt");
I added reading paths from config file for this one and for  the file with data to initialize the hotel too.

2022-12-25 16:56 UTC, asiajanicka commented on src/main/java/org/jjm/bookings/TransportBooking.java
> +    private static int counter = 0;
I use it only to print total number of transport bookings to the file with statistics

2022-12-27 21:14 UTC, vboltrukanis approved these changes

2022-12-28 14:56 UTC, merged